apiVersion: apps/v1
kind: Deployment
metadata:
  name: nageshupalanchi/my-apache-html-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nageshupalanchi/my-apache-html-site
  template:
    metadata:
      labels:
        app: nageshupalanchi/my-apache-html-site
    spec:
      containers:
      - name: MyApp
        image: nageshupalanchi/my-apache-html-site:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  type: NodePort
  selector:
    app: your-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30008
